from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

def generate_quotation_pdf(quotation_data: dict, project_name: str) -> BytesIO:
    try:
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        
        # Header
        c.setFont("Helvetica-Bold", 24)
        c.drawString(inch, height - inch, "ConstructFlow Quotation")
        c.setFont("Helvetica", 12)
        c.drawString(inch, height - 1.3*inch, f"Project: {project_name}")
        c.drawString(inch, height - 1.5*inch, f"Generated: AI Estimate")
        
        # Project Details
        y = height - 2*inch
        c.setFont("Helvetica-Bold", 14)
        c.drawString(inch, y, "Project Details")
        y -= 0.3*inch
        c.setFont("Helvetica", 12)
        c.drawString(inch, y, f"Timeline Estimated: {quotation_data.get('timeline_days', 0)} days")
        y -= 0.2*inch
        c.drawString(inch, y, f"AI Confidence Score: {quotation_data.get('confidence_score', 0)}%")
        
        # Cost Breakdown Table
        y -= 0.5*inch
        c.setFont("Helvetica-Bold", 14)
        c.drawString(inch, y, "Cost Breakdown")
        
        c.setFont("Helvetica", 12)
        y -= 0.3*inch
        c.drawString(inch, y, f"Material Cost: Rs. {quotation_data.get('material_cost', 0):,.2f}")
        y -= 0.2*inch
        c.drawString(inch, y, f"Labour Cost:   Rs. {quotation_data.get('labour_cost', 0):,.2f}")
        y -= 0.2*inch
        c.drawString(inch, y, f"Equipment Cost:Rs. {quotation_data.get('equipment_cost', 0):,.2f}")
        y -= 0.2*inch
        c.drawString(inch, y, f"Overhead:      Rs. {quotation_data.get('overhead', 0):,.2f}")
        
        y -= 0.4*inch
        c.setFont("Helvetica-Bold", 14)
        c.drawString(inch, y, f"TOTAL COST:    Rs. {quotation_data.get('total_cost', 0):,.2f}")
        
        # Footer
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(inch, 0.5*inch, "Generated by ConstructFlow AI - Not a final legal contract.")
        
        c.showPage()
        c.save()
        
        buffer.seek(0)
        return buffer
    except Exception as e:
        print(f"PDF generation error: {e}")
        raise e
