const {chromium} = require('C:/Users/UsEr/AppData/Local/npm-cache/_npx/e41f203b7505f1fb/node_modules/playwright');
const fs=require('node:fs'); const assert=require('node:assert/strict');
const env=fs.readFileSync('frontend/.env','utf8');
const base=env.match(/^EXPO_PUBLIC_SUPABASE_URL\s*=\s*["']?([^\s"']+)/m)[1];
const storageKey=`sb-${new URL(base).hostname.split('.')[0]}-auth-token`;
const user={id:'00000000-0000-0000-0000-000000000001',email:'test@example.invalid',role:'authenticated',aud:'authenticated',user_metadata:{role:'super_admin',full_name:'Report Test Admin'},app_metadata:{provider:'email'}};
const exp=Math.floor(Date.now()/1000)+3600;
const token=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:user.id,exp,role:'authenticated'})).toString('base64url')+'.test';
const fixture={generated_at:new Date().toISOString(),people:[{id:'pm1',full_name:'Project Manager'},{id:'w1',full_name:'Test Worker'}],projects:[{id:'p1',name:'Riverside Apartments',status:'In Progress',total_budget:1000000,spent_cost:1200000,completion_percentage:60,end_date:'2025-01-01',pm_id:'pm1'},{id:'p2',name:'Completed Office',status:'Completed',total_budget:500000,spent_cost:450000,completion_percentage:100,end_date:'2025-01-01',pm_id:'pm1'}],materials:[{id:'m1',name:'Cement',unit:'bags',current_stock:3,minimum_threshold:10},{id:'m2',name:'Steel',unit:'kg',current_stock:100,minimum_threshold:20}],orders:[{id:'o1',po_number:'PO-001',supplier_name:'Supplier One',status:'Confirmed',total_price:50000,expected_date:'2025-01-01',site_id:'p1'}],payroll:[{id:'s1',worker_id:'w1',site_id:'p1',total_amount:25000,total_days:10,total_overtime_hours:5,period_start:'2026-09-01',period_end:'2026-09-30',status:'Pending'},{id:'s2',worker_id:'w1',site_id:'p2',total_amount:20000,total_days:8,total_overtime_hours:0,period_start:'2026-08-01',period_end:'2026-08-31',status:'Paid'}]};
let browser;
(async()=>{
 browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:900},acceptDownloads:true});
 await page.addInitScript(({storageKey,session})=>localStorage.setItem(storageKey,JSON.stringify(session)),{storageKey,session:{access_token:token,refresh_token:'fixture-only',expires_at:exp,expires_in:3600,token_type:'bearer',user}});
 await page.route('**/rest/v1/**',r=>r.fulfill({json:[]}));
 await page.route('**/auth/v1/**',r=>r.fulfill({json:user}));
 await page.route('**/api/**',r=>r.fulfill({json:[]}));
 let mode='data';let calls=0;
 await page.route('**/reports/management',r=>{calls++;return mode==='error'?r.fulfill({status:500,json:{detail:'Test service unavailable'}}):r.fulfill({json:mode==='empty'?{...fixture,projects:[],materials:[],orders:[],payroll:[],people:[]}:fixture});});
 await page.routeWebSocket('**/realtime/**',ws=>ws.close());
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:8081/admin/reports',{waitUntil:'domcontentloaded',timeout:180000});
 await page.getByText('Management action agenda',{exact:true}).waitFor({timeout:120000});
 await page.screenshot({path:'.validation-web/reports-overview.png'});
 await page.getByRole('button',{name:'Project Performance',exact:true}).click();
 await page.getByText('Project decision register',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Over budget',exact:true}).click();
 await page.getByText('Showing 1 of 1 records',{exact:false}).waitFor();
 const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Export filtered projects (CSV)'}).click();
 const download=await downloaded;const content=fs.readFileSync(await download.path(),'utf8');assert(content.includes('Riverside Apartments'));assert(!content.includes('Completed Office'));
 await page.getByRole('button',{name:'Inventory & Procurement',exact:true}).click();
 await page.getByText('Inventory replenishment register',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Replenish',exact:true}).click();
 assert.equal(await page.getByText('Steel',{exact:true}).count(),0);
 await page.getByRole('button',{name:'Payroll & Workforce Cost',exact:true}).click();
 await page.getByText('Salary-slip register',{exact:true}).waitFor();
 await page.getByRole('button',{name:'All periods',exact:true}).click();
 await page.getByRole('button',{name:'Pending',exact:true}).click();
 await page.getByText('Showing 1 of 1 records',{exact:false}).waitFor();
 await page.getByText('Test Worker',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'.validation-web/reports-mobile.png'});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Page should not overflow horizontally');
 mode='error';await page.getByRole('button',{name:'Refresh data',exact:true}).click();await page.getByText('Report unavailable',{exact:true}).waitFor();
 mode='empty';await page.getByRole('button',{name:'Retry',exact:true}).click();await page.getByText('No records match these filters.',{exact:true}).waitFor();
 assert(calls>=6);assert.deepEqual(errors,[]);
 console.log('PASS overview, all drill-downs, project/stock/payroll filters, CSV contents, mobile overflow, refresh, error/retry and empty states. Mocked browser data; no production records changed.');
 await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exit(1)});
