const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const fs=require('fs'),assert=require('assert/strict'),path=require('path');
process.chdir(path.resolve(__dirname, '../..'));
fs.mkdirSync('.validation-web',{recursive:true});
const preview=process.env.RESPONSIVE_URL || 'http://localhost:8083';
const env=fs.readFileSync('frontend/.env','utf8'),base=env.match(/^EXPO_PUBLIC_SUPABASE_URL\s*=\s*["']?([^\s"']+)/m)[1],key=`sb-${new URL(base).hostname.split('.')[0]}-auth-token`;
const uid='00000000-0000-0000-0000-000000000001';
const profile={id:uid,role:'pm',full_name:'Site Test Manager',is_approved:true,email:'test@example.invalid'};
const projects=[{id:'p1',name:'Riverside Construction',status:'Active',location:'Colombo',pm_id:uid,total_budget:100000,total_spent:30000,client_id:'client1'},{id:'p2',name:'Hilltop Construction',status:'In Progress',location:'Kandy',pm_id:uid,total_budget:200000}];
const worker={id:'worker-record',profiles:{id:'worker-profile',full_name:'Test Worker',qr_code:'worker-qr'}};
const tables={projects,profiles:[profile],site_manager_sites:[{id:'s1',project_id:'p1',site_manager_id:uid},{id:'s2',project_id:'p2',site_manager_id:uid}],materials:[{id:'m1',project_id:'p1',name:'Portland Cement',unit:'bags',current_stock:3,minimum_threshold:10}],material_requests:[],purchase_orders:[{id:'po1',project_id:'p1',po_number:'PO-001',material_id:'m1',quantity_ordered:10,status:'Delivered',delivered_at:'2026-10-06T12:00:00Z'}],site_workers:[{id:'sw1',project_id:'p1',worker_id:worker.id,workers:worker}],attendance:[],site_issues:[],milestones:[{id:'ms1',project_id:'p1',title:'Foundation',description:'Foundation work',completion_percentage:25,status:'In Progress',due_date:'2026-11-01',milestone_media:[]}],site_reports:[],notifications:[]};
tables.profiles.push({id:'worker-profile',full_name:'Test Worker',role:'worker'},{id:'client1',full_name:'Test Client',role:'client',email:'client@example.invalid'});
tables.salary_slips=[{id:'slip1',site_id:'p1',worker_id:'worker-profile',total_amount:12500,total_days:5,total_overtime_hours:2,period_start:'2026-10-01',period_end:'2026-10-05',status:'Pending'}];
tables.material_requests=[{id:'rq1',project_id:'p1',item_name:'Sand',quantity:4,status:'Pending Approval',requested_by:'sm1'},{id:'rq2',project_id:'p1',item_name:'Bricks',quantity:200,status:'Pending Approval',requested_by:'sm1'}];
tables.attendance=[{id:'att1',site_id:'p1',worker_id:'worker-record',date:new Date().toISOString().slice(0,10),check_in_time:new Date().toISOString(),hours_worked:9,workers:{profiles:{full_name:'Test Worker'}}}];
const mutations=[],results=[],errors=[];
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(15000);
const dialogOK=page.locator('.bg-brand-orange').filter({hasText:/^OK$/});
await page.addLocatorHandler(dialogOK, async()=>{await dialogOK.click();});
const user={id:uid,email:profile.email,aud:'authenticated',role:'authenticated',user_metadata:profile,app_metadata:{provider:'email'}},exp=Math.floor(Date.now()/1000)+3600,token=Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:uid,exp,role:'authenticated'})).toString('base64url')+'.test';
await page.addInitScript(({key,session})=>localStorage.setItem(key,JSON.stringify(session)),{key,session:{access_token:token,refresh_token:'fixture-only',expires_at:exp,expires_in:3600,token_type:'bearer',user}});
page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(e.message));
await page.route('**/auth/v1/**',r=>r.fulfill({json:user}));await page.routeWebSocket('**/realtime/**',ws=>ws.close());
await page.route('**/rest/v1/**',async r=>{const req=r.request(),url=new URL(req.url()),name=url.pathname.split('/').pop();let rows=tables[name]||[];
for(const [k,v] of url.searchParams)if(v.startsWith('eq.'))rows=rows.filter(row=>String(row[k])===v.slice(3));
for(const [k,v] of url.searchParams)if(v.startsWith('in.('))rows=rows.filter(row=>v.slice(4,-1).split(',').includes(String(row[k])));
if(req.method()!=='GET'&&req.method()!=='HEAD'){const body=req.postDataJSON();mutations.push({name,method:req.method(),body});if(req.method()==='POST'){const row={id:name+'-new',...body,projects:projects.find(p=>p.id===body.project_id)};(tables[name]||=[]).push(row);rows=[row];}else if(req.method()==='PATCH'){rows.forEach(row=>Object.assign(row,body));}else if(req.method()==='DELETE'){tables[name]=(tables[name]||[]).filter(row=>!rows.includes(row));}}
await r.fulfill({json:req.headers().accept?.includes('object+json')?(rows[0]||{}):rows,headers:{'content-range':`0-${Math.max(0,rows.length-1)}/${rows.length}`}});});
await page.route('**/api/**',async r=>{const req=r.request(),url=new URL(req.url());let body;try{body=req.postDataJSON();}catch{body=req.postData();}mutations.push({name:url.pathname,method:req.method(),body});let data={};if(url.pathname.includes('/site-reports')&&req.method()==='GET')data=[];if(url.pathname.includes('/projects/')&&url.pathname.endsWith('/milestones')&&req.method()==='POST'){data={id:'ms-new',project_id:'p1',status:'Pending',...body};tables.milestones.push(data);} if(url.pathname.includes('/receive')){tables.purchase_orders[0].status='Received';tables.materials[0].current_stock+=10;data=tables.purchase_orders[0];}if(url.pathname.includes('/milestones/')&&req.method()!=='GET'){Object.assign(tables.milestones[0],body);data=tables.milestones[0];}if(url.pathname.includes('/site-reports')&&req.method()==='POST'){data={id:'report-new',site_manager_id:uid,...body};tables.site_reports.push(data);}if(url.pathname.includes('/media/upload'))data={url:'https://example.invalid/test-photo.jpg'};await r.fulfill({json:data});});
async function go(route){await page.goto(preview+'/pm/'+route,{waitUntil:'domcontentloaded',timeout:240000});await page.getByLabel('Open notifications',{exact:true}).first().waitFor();await page.waitForTimeout(500);}
async function test(name,fn){if(process.env.FLOW_ONLY&&!name.includes(process.env.FLOW_ONLY))return;try{await fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message.slice(0,250));await page.screenshot({path:'.validation-web/site-flow-failure.png'});}}

await test('approval, rejection and stock names',async()=>{await go('materials');await page.getByText('Approve',{exact:true}).first().click();await page.getByText('Approved',{exact:true}).last().waitFor();assert.equal(tables.material_requests[0].status,'Approved');await page.getByText('Reject',{exact:true}).click();await page.getByText('Confirm Rejection',{exact:true}).click();assert.equal(tables.material_requests[1].status,'Pending Approval');await page.getByPlaceholder('Reason for rejection').fill('Quantity exceeds current need');await page.getByText('Confirm Rejection',{exact:true}).click();await page.getByText('Rejected',{exact:true}).last().waitFor();assert.equal(tables.material_requests[1].notes,'Quantity exceeds current need');await page.getByText('Site Stock',{exact:true}).click();await page.getByText('Portland Cement',{exact:true}).waitFor();});
await test('payroll uses saved slips and opens details',async()=>{await go('payroll');await page.getByLabel('View salary slip slip1').click();await page.getByText('Salary Slip Details',{exact:true}).waitFor();await page.getByText('Days worked: 5',{exact:true}).waitFor();await page.getByText('Close',{exact:true}).click();await page.getByText('Paid',{exact:true}).click();await page.getByText('No salary slips match these filters.',{exact:true}).waitFor();});
await test('purchase-order routes resolve',async()=>{await go('materials');await page.getByText('Purchase Orders',{exact:true}).click();await page.getByText('View Order',{exact:true}).click();await page.waitForURL('**/pm/materials/orders/po1');await page.getByText('PO-001',{exact:true}).first().waitFor();await go('materials/orders/create');await page.getByText('Submit Order',{exact:true}).waitFor();});
await test('milestone completion persists percentage',async()=>{await go('projects/p1/milestones');await page.getByText('Mark Complete',{exact:true}).click();await page.getByText('Completed',{exact:true}).first().waitFor();assert.equal(tables.milestones[0].completion_percentage,100);});
await test('milestone creation validates date and saves',async()=>{await go('projects/p1/milestones');await page.getByText('+ Add Milestone',{exact:true}).click();await page.getByPlaceholder('e.g. Foundation Complete').fill('Roof inspection');await page.getByPlaceholder('2025-06-01').fill('2026-02-30');await page.getByText('Add Milestone',{exact:true}).click();assert.equal(tables.milestones.length,1);await page.getByPlaceholder('2025-06-01').fill('2026-11-20');await page.getByText('Add Milestone',{exact:true}).click();await page.getByText('Roof inspection',{exact:true}).waitFor();assert.equal(tables.milestones[1].due_date,'2026-11-20');});
await test('PM client details are read-only',async()=>{await go('client');await page.getByText('Test Client',{exact:true}).waitFor();await page.getByText('View Details',{exact:true}).click();await page.getByText('Client Details',{exact:true}).waitFor();assert.equal(await page.getByText('Delete',{exact:true}).count(),0);assert.equal(await page.getByText('Edit',{exact:true}).count(),0);await page.getByText('Close',{exact:true}).click();});
await test('query error recovers',async()=>{await page.route('**/rest/v1/material_requests?**',r=>r.fulfill({status:500,json:{message:'Requests unavailable'}}),{times:1});await go('materials');await page.getByText('Requests unavailable',{exact:true}).waitFor();await page.getByText('Refresh',{exact:true}).click();await page.getByText('Sand',{exact:true}).waitFor();});
for(const route of ['dashboard','projects','projects/p1','projects/p1/milestones','projects/p1/milestones/create','projects/p1/expenses','projects/p1/reports','materials','materials/orders/create','materials/orders/po1','payroll','labour','team','suppliers','client','estimator','notifications','profile','settings'])await test(route+' responsive',async()=>{await go(route);assert.equal(await page.getByText('Unmatched Route',{exact:true}).count(),0);for(const [width,height] of [[320,568],[768,1024],[1440,900]]){await page.setViewportSize({width,height});await page.waitForTimeout(200);const outside=await page.evaluate(()=>[...document.querySelectorAll('input,button,[role="button"]')].filter(e=>{const r=e.getBoundingClientRect();if(!r.width||!r.height||r.right<=0)return false;for(let p=e.parentElement;p;p=p.parentElement){if(['auto','scroll'].includes(getComputedStyle(p).overflowX)&&p.scrollWidth>p.clientWidth+1)return false;}return r.left< -1||r.right>innerWidth+1;}).map(e=>e.textContent.slice(0,70)));assert.deepEqual(outside,[],width+'px controls outside viewport');}await page.setViewportSize({width:390,height:844});});
fs.writeFileSync('.validation-web/pm-flow-results.json',JSON.stringify({results,errors,mutations},null,2));await browser.close();if(results.some(r=>!r.pass)||errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
