import React, { useCallback, useState } from 'react';
import { View, Text, ScrollView, ActivityIndicator } from 'react-native';
import { useFocusEffect, useLocalSearchParams } from 'expo-router';
import { TopNav } from '@/components/common/TopNav';
import { managedProjects } from '@/services/pmData';
import { supabase } from '@/lib/supabase';
import { formatMoney } from '@/utils/format';
export default function PMProjectCosts(){
  const {id}=useLocalSearchParams<{id:string}>();
  const [project,setProject]=useState<any>(null),[orders,setOrders]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const selected=(await managedProjects()).find(p=>p.id===id);if(!selected)throw new Error('This project is not assigned to you.');setProject(selected);const result=await supabase.from('purchase_orders').select('*').eq('project_id',id).order('created_at',{ascending:false});if(result.error)throw result.error;setOrders(result.data||[]);}catch(e:any){setError(e.message);}finally{setLoading(false);}},[id]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  const money=(value:any)=>value==null?'Not recorded':formatMoney(Number(value));
  return <View className="flex-1 bg-brand-light"><TopNav title="Budget & Procurement" showBackButton actionLabel="Refresh" onActionPress={load}/><ScrollView keyboardShouldPersistTaps="handled" className="flex-1 p-4">{!!error&&<Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-red-600 mb-4">{error}</Text>}{loading?<ActivityIndicator color="#F97316"/>:project&&<><Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-xl font-bold mb-4">{project.name}</Text><View className="bg-white rounded-xl p-5 mb-4"><Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3}>Project budget: {money(project.total_budget)}</Text><Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="mt-3">Recorded project spend: {money(project.spent_cost)}</Text>{project.total_budget!=null&&project.spent_cost!=null&&<Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="font-bold mt-3">Budget balance: {money(Number(project.total_budget)-Number(project.spent_cost))}</Text>}</View><Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-lg font-bold mb-2">Purchase Orders</Text><Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-gray-500 mb-4">Order values are procurement commitments and may differ from recorded project spend.</Text>{!orders.length&&<Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3}>No purchase orders for this project.</Text>}{orders.map(o=><View key={o.id} className="bg-white rounded-xl p-5 mb-3"><Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="font-bold">{o.po_number}</Text><Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="mt-2">{o.items}</Text><Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="mt-2">{money(o.total_price)} | {o.status}</Text></View>)}</>}</ScrollView></View>;
}
