import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, ActivityIndicator } from 'react-native';
import { supabase } from '../../../lib/supabase';
import { TopNav } from '@/components/common/TopNav';
import { Ionicons } from '@expo/vector-icons';

export default function WorkerPayrollPage() {
  const [loading, setLoading] = useState(true);
  const [payrollRecords, setPayrollRecords] = useState<any[]>([]);
  const [profile, setProfile] = useState<any>(null);
  const [attendanceSummary, setAttendanceSummary] = useState({ present: 0 });

  useEffect(() => {
    let isMounted = true;

    const fetchPayrollData = async () => {
      try {
        const { data: sessionData } = await supabase.auth.getSession();
        if (!sessionData?.session) return;
        const userId = sessionData.session.user.id;

        const [profileReq, payrollReq, attendanceReq] = await Promise.all([
          supabase.from('profiles').select('*, labour(daily_wage, id)').eq('id', userId).single(),
          supabase.from('payroll').select('*').eq('worker_id', userId).order('created_at', { ascending: false }),
          supabase.from('attendance').select('id', { count: 'exact', head: true }).eq('worker_id', userId).eq('status', 'Present'),
        ]);

        if (isMounted) {
          setProfile(profileReq.data);
          setPayrollRecords(payrollReq.data || []);
          setAttendanceSummary({ present: attendanceReq.count || 0 });
        }
      } catch (error) {
        console.error('Worker payroll error:', error);
      } finally {
        if (isMounted) setLoading(false);
      }
    };

    fetchPayrollData();
    return () => { isMounted = false; };
  }, []);

  const dailyWage = profile?.labour?.[0]?.daily_wage || 0;
  const estimatedEarnings = dailyWage * attendanceSummary.present;

  const formatCurrency = (amount: number) => `LKR ${amount.toLocaleString('en-LK')}`;

  return (
    <View className="flex-1 bg-brand-light">
      <TopNav title="My Payroll" showAction={false} />

      {loading ? (
        <View className="flex-1 items-center justify-center">
          <ActivityIndicator size="large" color="#F97316" />
        </View>
      ) : (
        <ScrollView className="flex-1 p-8" showsVerticalScrollIndicator={false}>

          {/* Earnings Summary Banner */}
          <View className="bg-gradient-to-r from-brand-orange to-orange-400 rounded-2xl p-8 mb-6 shadow-md bg-brand-orange">
            <Text className="text-white text-sm font-semibold mb-1 opacity-80">Estimated Total Earnings</Text>
            <Text className="text-white text-4xl font-bold">{formatCurrency(estimatedEarnings)}</Text>
            <View className="flex-row mt-4 gap-6">
              <View>
                <Text className="text-white opacity-70 text-xs">Daily Rate</Text>
                <Text className="text-white font-bold mt-1">{formatCurrency(dailyWage)}</Text>
              </View>
              <View>
                <Text className="text-white opacity-70 text-xs">Days Worked</Text>
                <Text className="text-white font-bold mt-1">{attendanceSummary.present}</Text>
              </View>
            </View>
          </View>

          {/* Payroll History */}
          <Text className="text-lg font-bold text-gray-800 mb-4">Salary Slips</Text>
          
          {payrollRecords.length === 0 ? (
            <View className="bg-white rounded-2xl p-12 shadow-sm border border-gray-100 items-center justify-center">
              <Ionicons name="document-text-outline" size={48} color="#E5E7EB" />
              <Text className="text-gray-400 mt-4 font-medium">No salary slips generated yet.</Text>
              <Text className="text-gray-400 text-sm mt-2 text-center">Salary slips are generated by your Project Manager at the end of each pay period.</Text>
            </View>
          ) : (
            <View className="space-y-4">
              {payrollRecords.map(record => (
                <View key={record.id} className="bg-white rounded-xl border border-gray-200 overflow-hidden shadow-sm">
                  <View className="flex-row items-center justify-between p-5 border-b border-gray-100 bg-gray-50">
                    <View>
                      <Text className="font-bold text-gray-800">
                        Pay Period: {new Date(record.period_start).toLocaleDateString('en-GB', { month: 'short', year: 'numeric' })}
                      </Text>
                      <Text className="text-gray-500 text-xs mt-0.5">
                        {new Date(record.period_start).toLocaleDateString()} – {new Date(record.period_end).toLocaleDateString()}
                      </Text>
                    </View>
                    <View className={`px-3 py-1.5 rounded-full ${record.status === 'Paid' ? 'bg-green-100' : 'bg-yellow-100'}`}>
                      <Text className={`text-xs font-bold ${record.status === 'Paid' ? 'text-green-700' : 'text-yellow-700'}`}>
                        {record.status}
                      </Text>
                    </View>
                  </View>
                  <View className="p-5 flex-row justify-between">
                    <View>
                      <Text className="text-gray-500 text-xs">Days Worked</Text>
                      <Text className="font-bold text-gray-800 mt-1">{record.days_worked}</Text>
                    </View>
                    <View>
                      <Text className="text-gray-500 text-xs">Daily Rate</Text>
                      <Text className="font-bold text-gray-800 mt-1">{formatCurrency(record.daily_rate || 0)}</Text>
                    </View>
                    <View>
                      <Text className="text-gray-500 text-xs">Gross Pay</Text>
                      <Text className="font-bold text-brand-orange mt-1 text-lg">{formatCurrency(record.gross_pay || 0)}</Text>
                    </View>
                  </View>
                </View>
              ))}
            </View>
          )}
        </ScrollView>
      )}
    </View>
  );
}
