import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, ActivityIndicator } from 'react-native';
import { supabase } from '../../../lib/supabase';
import { TopNav } from '@/components/common/TopNav';
import { Ionicons } from '@expo/vector-icons';

export default function WorkerPayrollPage() {
  const [loading, setLoading] = useState(true);
  const [payrollRecords, setPayrollRecords] = useState<any[]>([]);
  const [profile, setProfile] = useState<any>(null);
  const [attendanceSummary, setAttendanceSummary] = useState({ present: 0 });

  useEffect(() => {
    let isMounted = true;

    const fetchPayrollData = async () => {
      try {
        const { data: sessionData } = await supabase.auth.getSession();
        if (!sessionData?.session) return;
        const userId = sessionData.session.user.id;

        const profileReq = await supabase.from('profiles').select('*').eq('id', userId).single();
        const workerName = profileReq.data?.full_name;

        let presentCount = 0;
        let salarySlips: any[] = [];

        if (workerName) {
          const [attendanceReq, payrollReq] = await Promise.all([
            supabase.from('labour').select('id', { count: 'exact', head: true }).eq('worker_name', workerName).eq('status', 'Present'),
            supabase.from('salary_slips').select('*').eq('worker_id', userId).order('created_at', { ascending: false }),
          ]);
          presentCount = attendanceReq.count || 0;
          salarySlips = payrollReq.data || [];
        }

        if (isMounted) {
          setProfile(profileReq.data);
          setPayrollRecords(salarySlips);
          setAttendanceSummary({ present: presentCount });
        }
      } catch (error) {
        console.error('Worker payroll error:', error);
      } finally {
        if (isMounted) setLoading(false);
      }
    };

    fetchPayrollData();
    return () => { isMounted = false; };
  }, []);

  const dailyWage = 3500; // Base daily rate (Rs. 3,500 as per payroll system)
  const estimatedEarnings = dailyWage * attendanceSummary.present;

  const formatCurrency = (amount: number) => `LKR ${amount.toLocaleString('en-LK')}`;

  return (
    <View className="flex-1 bg-brand-light">
      <TopNav title="My Payroll" showAction={false} />

      {loading ? (
        <View className="flex-1 items-center justify-center">
          <ActivityIndicator size="large" color="#F97316" />
        </View>
      ) : (
        <ScrollView keyboardShouldPersistTaps="handled" className="flex-1 p-4 md:p-6 lg:p-8" showsVerticalScrollIndicator={false}>

          {/* Earnings Summary Banner */}
          <View className="bg-gradient-to-r from-brand-orange to-orange-400 rounded-2xl p-8 mb-6 shadow-md bg-brand-orange">
            <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-white text-sm font-semibold mb-1 opacity-80">Estimated Total Earnings</Text>
            <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-white text-4xl font-bold">{formatCurrency(estimatedEarnings)}</Text>
            <View className="flex-row mt-4 gap-6">
              <View>
                <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-white opacity-70 text-xs">Daily Rate</Text>
                <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-white font-bold mt-1">{formatCurrency(dailyWage)}</Text>
              </View>
              <View>
                <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-white opacity-70 text-xs">Days Worked</Text>
                <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-white font-bold mt-1">{attendanceSummary.present}</Text>
              </View>
            </View>
          </View>

          {/* Payroll History */}
          <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-lg font-bold text-gray-800 mb-4">Salary Slips</Text>
          
          {payrollRecords.length === 0 ? (
            <View className="bg-white rounded-2xl p-12 shadow-sm border border-gray-100 items-center justify-center">
              <Ionicons name="document-text-outline" size={48} color="#E5E7EB" />
              <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-gray-400 mt-4 font-medium">No salary slips generated yet.</Text>
              <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-gray-400 text-sm mt-2 text-center">Salary slips are generated by your Project Manager at the end of each pay period.</Text>
            </View>
          ) : (
            <View className="space-y-4">
              {payrollRecords.map(record => (
                <View key={record.id} className="bg-white rounded-xl border border-gray-200 overflow-hidden shadow-sm">
                  <View className="flex-row items-center justify-between p-5 border-b border-gray-100 bg-gray-50">
                    <View>
                      <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="font-bold text-gray-800">
                        Pay Period: {new Date(record.period_start).toLocaleDateString('en-GB', { month: 'short', year: 'numeric' })}
                      </Text>
                      <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-gray-500 text-xs mt-0.5">
                        {new Date(record.period_start).toLocaleDateString()} – {new Date(record.period_end).toLocaleDateString()}
                      </Text>
                    </View>
                    <View className={`px-3 py-1.5 rounded-full ${record.status === 'Paid' ? 'bg-green-100' : 'bg-yellow-100'}`}>
                      <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className={`text-xs font-bold ${record.status === 'Paid' ? 'text-green-700' : 'text-yellow-700'}`}>
                        {record.status}
                      </Text>
                    </View>
                  </View>
                  <View className="p-5 flex-row justify-between">
                    <View>
                      <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-gray-500 text-xs">Days Worked</Text>
                      <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="font-bold text-gray-800 mt-1">{record.total_days || 0}</Text>
                    </View>
                    <View>
                      <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-gray-500 text-xs">Overtime Hrs</Text>
                      <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="font-bold text-gray-800 mt-1">{record.overtime_hours || 0} hrs</Text>
                    </View>
                    <View>
                      <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="text-gray-500 text-xs">Total Payout</Text>
                      <Text style={{ flexShrink: 1, minWidth: 0 }} maxFontSizeMultiplier={1.3} className="font-bold text-brand-orange mt-1 text-lg">{formatCurrency(record.total_payout || 0)}</Text>
                    </View>
                  </View>
                </View>
              ))}
            </View>
          )}
        </ScrollView>
      )}
    </View>
  );
}
